[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"

[[services]]
name = "fullstack-chess-app"

[build.watchPatterns]
include = ["backend/**", "frontend/**", "package.json"]