import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

if (typeof window === "undefined") {
  const globalWithStorage = globalThis as typeof globalThis & {
    localStorage?: Storage;
  };

  const storage = globalWithStorage.localStorage;
  const isBrokenStorage =
    !storage ||
    typeof storage.getItem !== "function" ||
    typeof storage.setItem !== "function" ||
    typeof storage.removeItem !== "function" ||
    typeof storage.clear !== "function";

  if (isBrokenStorage) {
    const store = new Map<string, string>();
    const storageShim: Storage = {
      get length() {
        return store.size;
      },
      getItem: (key: string) => store.get(key) ?? null,
      key: (index: number) => Array.from(store.keys())[index] ?? null,
      setItem: (key: string, value: string) => {
        store.set(key, value);
      },
      removeItem: (key: string) => {
        store.delete(key);
      },
      clear: () => {
        store.clear();
      },
    };

    (globalThis as { localStorage?: Storage }).localStorage = storageShim;
  }
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chess App",
  description: "Generated by Zahra Shahab",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
        <ToastContainer position="top-right" autoClose={2000} aria-label="Notification" />
      </body>
    </html>
  );
}
